export const ADD_NUMBER = "ADD_NUMBER";

export enum UserActionTypes {
  VALIDATE_USER = "VALIDATE_USER",
  VALIDATE_USER_PENDING = "VALIDATE_USER_PENDING",
  VALIDATE_USER_FULFILLED = "VALIDATE_USER_FULFILLED",
  VALIDATE_USER_REJECTED = "VALIDATE_USER_REJECTED"
}
