export const ADD_NUMBER = "ADD_NUMBER";

export enum UserActionTypes {
  VALIDATE_USER = "VALIDATE_USER",
  QUICK_VALIDATE_USER = "QUICK_VALIDATE_USER",
  QUICK_VALIDATE_USER_FULFILLED = "QUICK_VALIDATE_USER_FULFILLED",
  VALIDATE_USER_PENDING = "VALIDATE_USER_PENDING",
  VALIDATE_USER_FULFILLED = "VALIDATE_USER_FULFILLED",
  VALIDATE_USER_REJECTED = "VALIDATE_USER_REJECTED",
  UPDATE_USER = "UPDATE_USER",
  UPDATE_USER_PENDING = "UPDATE_USER_PENDING",
  UPDATE_USER_FULFILLED = "UPDATE_USER_FULFILLED",
  UPDATE_USER_REJECTED = "UPDATE_USER_REJECTED",
  UPDATE_USER_PASS = "UPDATE_USER_PASS",
  UPDATE_USER_PASS_PENDING = "UPDATE_USER_PASS_PENDING",
  UPDATE_USER_PASS_FULFILLED = "UPDATE_USER_PASS_FULFILLED",
  UPDATE_USER_PASS_REJECTED = "UPDATE_USER_PASS_REJECTED"
}

export enum TournamentActionTypes {
  RETRIEVE_TOURNAMENTS = "RETRIEVE_TOURNAMENTS",
  RETRIEVE_TOURNAMENTS_PENDING = "RETRIEVE_TOURNAMENTS_PENDING",
  RETRIEVE_TOURNAMENTS_FULFILLED = "RETRIEVE_TOURNAMENTS_FULFILLED",
  RETRIEVE_TOURNAMENTS_REJECTED = "RETRIEVE_TOURNAMENTS_REJECTED",
  SELECT_TOURNAMENT = "SELECT_TOURNAMENT",
  SELECT_TOURNAMENT_TOURNAMENT_PENDING = "SELECT_TOURNAMENT_TOURNAMENT_PENDING",
  SELECT_TOURNAMENT_TOURNAMENT_FULFILLED = "SELECT_TOURNAMENT_TOURNAMENT_FULFILLED",
  SELECT_TOURNAMENT_TOURNAMENT_REJECTED = "SELECT_TOURNAMENT_TOURNAMENT_REJECTED",
  CREATE_TOURNAMENTS = "CREATE_TOURNAMENTS",
  CREATE_TOURNAMENTS_PENDING = "CREATE_TOURNAMENTS_PENDING",
  CREATE_TOURNAMENTS_FULFILLED = "CREATE_TOURNAMENTS_FULFILLED",
  CREATE_TOURNAMENTS_REJECTED = "CREATE_TOURNAMENTS_REJECTED"
}
