export const ADD_NUMBER = "ADD_NUMBER";

export enum UserActionTypes {
  VALIDATE_USER = "VALIDATE_USER",
  QUICK_VALIDATE_USER = "QUICK_VALIDATE_USER",
  QUICK_VALIDATE_USER_FULFILLED = "QUICK_VALIDATE_USER_FULFILLED",
  VALIDATE_USER_PENDING = "VALIDATE_USER_PENDING",
  VALIDATE_USER_FULFILLED = "VALIDATE_USER_FULFILLED",
  VALIDATE_USER_REJECTED = "VALIDATE_USER_REJECTED",
  UPDATE_USER = "UPDATE_USER",
  UPDATE_USER_PENDING = "UPDATE_USER_PENDING",
  UPDATE_USER_FULFILLED = "UPDATE_USER_FULFILLED",
  UPDATE_USER_REJECTED = "UPDATE_USER_REJECTED",
  UPDATE_USER_PASS = "UPDATE_USER_PASS",
  UPDATE_USER_PASS_PENDING = "UPDATE_USER_PASS_PENDING",
  UPDATE_USER_PASS_FULFILLED = "UPDATE_USER_PASS_FULFILLED",
  UPDATE_USER_PASS_REJECTED = "UPDATE_USER_PASS_REJECTED"
}
